// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentApi.Data;

#nullable disable

namespace RecruitmentApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210105549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Interview_Panel", b =>
                {
                    b.Property<string>("user_id")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int>("interview_id")
                        .HasColumnType("int");

                    b.HasKey("user_id", "interview_id");

                    b.HasIndex("interview_id");

                    b.ToTable("Interview_Panel", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate", b =>
                {
                    b.Property<string>("candidate_id")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("resume_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("candidate_id");

                    b.HasIndex(new[] { "email" }, "UQ_Candidates_Email")
                        .IsUnique();

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Document", b =>
                {
                    b.Property<int>("document_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("document_id"));

                    b.Property<string>("candidate_id")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("document_type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("file_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("uploaded_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("verification_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("document_id");

                    b.HasIndex("candidate_id");

                    b.ToTable("Candidate_Documents");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Review", b =>
                {
                    b.Property<int>("review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("review_id"));

                    b.Property<string>("candidate_id")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("reviewed_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("review_id");

                    b.HasIndex("candidate_id");

                    b.HasIndex("job_id");

                    b.HasIndex("user_id");

                    b.ToTable("Candidate_Reviews");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Skill", b =>
                {
                    b.Property<int>("candidate_skill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("candidate_skill_id"));

                    b.Property<string>("candidate_id")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int>("skill_id")
                        .HasColumnType("int");

                    b.Property<int>("years_experience")
                        .HasColumnType("int");

                    b.HasKey("candidate_skill_id");

                    b.HasIndex("candidate_id");

                    b.HasIndex("skill_id");

                    b.ToTable("Candidate_Skills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Status_History", b =>
                {
                    b.Property<int>("candidate_status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("candidate_status_id"));

                    b.Property<string>("candidate_id")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("changed_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("changed_by")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.Property<string>("reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("candidate_status_id");

                    b.HasIndex("candidate_id");

                    b.HasIndex("changed_by");

                    b.HasIndex("job_id");

                    b.ToTable("Candidate_Status_History", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Employee_Record", b =>
                {
                    b.Property<string>("employee_id")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("candidate_id")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("joining_date")
                        .HasColumnType("date");

                    b.Property<string>("offer_letter_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("employee_id");

                    b.HasIndex("job_id");

                    b.HasIndex(new[] { "candidate_id" }, "UQ_Employee_Records_Candidate")
                        .IsUnique();

                    b.ToTable("Employee_Records");
                });

            modelBuilder.Entity("RecruitmentApi.Models.HR_Review", b =>
                {
                    b.Property<int>("review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("review_id"));

                    b.Property<int>("adaptability_rating")
                        .HasColumnType("int");

                    b.Property<string>("areas_for_improvement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("career_path_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("communication_rating")
                        .HasColumnType("int");

                    b.Property<int>("interview_id")
                        .HasColumnType("int");

                    b.Property<int>("interview_id1")
                        .HasColumnType("int");

                    b.Property<int>("leadership_rating")
                        .HasColumnType("int");

                    b.Property<int>("overall_rating")
                        .HasColumnType("int");

                    b.Property<string>("strengths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("teamwork_rating")
                        .HasColumnType("int");

                    b.Property<string>("training_recommendations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id1")
                        .IsRequired()
                        .HasColumnType("char(8)");

                    b.HasKey("review_id");

                    b.HasIndex("interview_id1");

                    b.HasIndex("user_id1");

                    b.ToTable("HR_Review");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview", b =>
                {
                    b.Property<int>("interview_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("interview_id"));

                    b.Property<string>("candidate_id")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("interview_type_id")
                        .HasColumnType("int");

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.Property<string>("location_or_link")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("mode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("round_number")
                        .HasColumnType("int");

                    b.Property<string>("scheduled_by")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("interview_id")
                        .HasName("PK_Interviews");

                    b.HasIndex("candidate_id");

                    b.HasIndex("interview_type_id");

                    b.HasIndex("job_id");

                    b.HasIndex("scheduled_by");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview_Feedback", b =>
                {
                    b.Property<int>("feedback_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("feedback_id"));

                    b.Property<int>("candidate_skill_id")
                        .HasColumnType("int");

                    b.Property<string>("comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("concept_rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("feedback_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("interview_id")
                        .HasColumnType("int");

                    b.Property<int>("technical_rating")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("feedback_id");

                    b.HasIndex("candidate_skill_id");

                    b.HasIndex("interview_id");

                    b.HasIndex("user_id");

                    b.ToTable("Interview_Feedback", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview_Type", b =>
                {
                    b.Property<int>("interview_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("interview_type_id"));

                    b.Property<string>("interview_round_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("process_descreption")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("interview_type_id");

                    b.ToTable("Interview_Type", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Job", b =>
                {
                    b.Property<int>("job_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("job_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("job_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("scheduled")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("status_id")
                        .HasColumnType("int");

                    b.HasKey("job_id");

                    b.HasIndex("created_by");

                    b.HasIndex("status_id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Skill", b =>
                {
                    b.Property<int>("skill_id")
                        .HasColumnType("int");

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.Property<string>("skill_type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("skill_id", "job_id");

                    b.HasIndex("job_id");

                    b.ToTable("Jobs_Skills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Status", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("status_id"));

                    b.Property<DateTime>("changed_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("changed_by")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("status_id");

                    b.HasIndex("changed_by");

                    b.ToTable("Jobs_Status", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Notification", b =>
                {
                    b.Property<int>("notification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notification_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unread");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("notification_id");

                    b.HasIndex("user_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Role", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Skill", b =>
                {
                    b.Property<int>("skill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("skill_id"));

                    b.Property<string>("skill_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("skill_id");

                    b.HasIndex(new[] { "skill_name" }, "UQ_Skills_Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.User", b =>
                {
                    b.Property<string>("user_id")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("user_id");

                    b.HasIndex(new[] { "email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Users_Role", b =>
                {
                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("role_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("Users_Roles", (string)null);
                });

            modelBuilder.Entity("Interview_Panel", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Interview", null)
                        .WithMany()
                        .HasForeignKey("interview_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Panel_Interviews");

                    b.HasOne("RecruitmentApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Panel_Users");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Document", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "candidate")
                        .WithMany("Candidate_Documents")
                        .HasForeignKey("candidate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Documents_Candidates");

                    b.Navigation("candidate");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Review", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "candidate")
                        .WithMany("Candidate_Reviews")
                        .HasForeignKey("candidate_id")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Reviews_Candidates");

                    b.HasOne("RecruitmentApi.Models.Job", "job")
                        .WithMany("Candidate_Reviews")
                        .HasForeignKey("job_id")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Reviews_Jobs");

                    b.HasOne("RecruitmentApi.Models.User", "user")
                        .WithMany("Candidate_Reviews")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Reviews_Users");

                    b.Navigation("candidate");

                    b.Navigation("job");

                    b.Navigation("user");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Skill", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "candidate")
                        .WithMany("Candidate_Skills")
                        .HasForeignKey("candidate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Skills_Candidates");

                    b.HasOne("RecruitmentApi.Models.Skill", "skill")
                        .WithMany("Candidate_Skills")
                        .HasForeignKey("skill_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Skills_Skills");

                    b.Navigation("candidate");

                    b.Navigation("skill");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Status_History", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "candidate")
                        .WithMany("Candidate_Status_Histories")
                        .HasForeignKey("candidate_id")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Status_History_Candidates");

                    b.HasOne("RecruitmentApi.Models.User", "changed_by_user")
                        .WithMany("Candidate_Status_Histories")
                        .HasForeignKey("changed_by")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Status_History_Users");

                    b.HasOne("RecruitmentApi.Models.Job", "job")
                        .WithMany("Candidate_Status_Histories")
                        .HasForeignKey("job_id")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Status_History_Jobs");

                    b.Navigation("candidate");

                    b.Navigation("changed_by_user");

                    b.Navigation("job");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Employee_Record", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "candidate")
                        .WithOne("Employee_Record")
                        .HasForeignKey("RecruitmentApi.Models.Employee_Record", "candidate_id")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Records_Candidates");

                    b.HasOne("RecruitmentApi.Models.Job", "job")
                        .WithMany("Employee_Records")
                        .HasForeignKey("job_id")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Records_Jobs");

                    b.Navigation("candidate");

                    b.Navigation("job");
                });

            modelBuilder.Entity("RecruitmentApi.Models.HR_Review", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Interview", "interview")
                        .WithMany("HR_Reviews")
                        .HasForeignKey("interview_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentApi.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("interview");

                    b.Navigation("user");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "candidate")
                        .WithMany("Interviews")
                        .HasForeignKey("candidate_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Interviews_Candidates");

                    b.HasOne("RecruitmentApi.Models.Interview_Type", "interview_type")
                        .WithMany("Interviews")
                        .HasForeignKey("interview_type_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Interviews_Interview_Type");

                    b.HasOne("RecruitmentApi.Models.Job", "job")
                        .WithMany("Interviews")
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Interviews_Jobs");

                    b.HasOne("RecruitmentApi.Models.User", "scheduled_by_user")
                        .WithMany("ScheduledInterviews")
                        .HasForeignKey("scheduled_by")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Interviews_Users");

                    b.Navigation("candidate");

                    b.Navigation("interview_type");

                    b.Navigation("job");

                    b.Navigation("scheduled_by_user");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview_Feedback", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate_Skill", "candidate_skill")
                        .WithMany("Interview_Feedbacks")
                        .HasForeignKey("candidate_skill_id")
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Feedback_CandidateSkills");

                    b.HasOne("RecruitmentApi.Models.Interview", "interview")
                        .WithMany("Interview_Feedbacks")
                        .HasForeignKey("interview_id")
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Feedback_Interviews");

                    b.HasOne("RecruitmentApi.Models.User", "user")
                        .WithMany("Interview_Feedbacks")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Feedback_Users");

                    b.Navigation("candidate_skill");

                    b.Navigation("interview");

                    b.Navigation("user");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Job", b =>
                {
                    b.HasOne("RecruitmentApi.Models.User", "created_by_user")
                        .WithMany("Jobs")
                        .HasForeignKey("created_by")
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Users");

                    b.HasOne("RecruitmentApi.Models.Jobs_Status", "status")
                        .WithMany("Jobs")
                        .HasForeignKey("status_id")
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Jobs_Status");

                    b.Navigation("created_by_user");

                    b.Navigation("status");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Skill", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Job", "job")
                        .WithMany("Jobs_Skills")
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Skills_Jobs");

                    b.HasOne("RecruitmentApi.Models.Skill", "skill")
                        .WithMany("Jobs_Skills")
                        .HasForeignKey("skill_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Skills_Skills");

                    b.Navigation("job");

                    b.Navigation("skill");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Status", b =>
                {
                    b.HasOne("RecruitmentApi.Models.User", "changed_by_user")
                        .WithMany("Jobs_Statuses")
                        .HasForeignKey("changed_by")
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Status_Users");

                    b.Navigation("changed_by_user");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Notification", b =>
                {
                    b.HasOne("RecruitmentApi.Models.User", "user")
                        .WithMany("Notifications")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Users_Role", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles_Roles");

                    b.HasOne("RecruitmentApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles_Users");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate", b =>
                {
                    b.Navigation("Candidate_Documents");

                    b.Navigation("Candidate_Reviews");

                    b.Navigation("Candidate_Skills");

                    b.Navigation("Candidate_Status_Histories");

                    b.Navigation("Employee_Record");

                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Skill", b =>
                {
                    b.Navigation("Interview_Feedbacks");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview", b =>
                {
                    b.Navigation("HR_Reviews");

                    b.Navigation("Interview_Feedbacks");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview_Type", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Job", b =>
                {
                    b.Navigation("Candidate_Reviews");

                    b.Navigation("Candidate_Status_Histories");

                    b.Navigation("Employee_Records");

                    b.Navigation("Interviews");

                    b.Navigation("Jobs_Skills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Status", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Skill", b =>
                {
                    b.Navigation("Candidate_Skills");

                    b.Navigation("Jobs_Skills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.User", b =>
                {
                    b.Navigation("Candidate_Reviews");

                    b.Navigation("Candidate_Status_Histories");

                    b.Navigation("Interview_Feedbacks");

                    b.Navigation("Jobs");

                    b.Navigation("Jobs_Statuses");

                    b.Navigation("Notifications");

                    b.Navigation("ScheduledInterviews");
                });
#pragma warning restore 612, 618
        }
    }
}
