// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentApi.Data;

#nullable disable

namespace RecruitmentApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103103957_RestoreHangfireIndexes")]
    partial class RestoreHangfireIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Candidate_Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("DocumentId");

                    b.HasIndex("CandidateId");

                    b.ToTable("Candidate_Documents");
                });

            modelBuilder.Entity("Interview_Panel", b =>
                {
                    b.Property<string>("user_id")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int>("interview_id")
                        .HasColumnType("int");

                    b.HasKey("user_id", "interview_id");

                    b.HasIndex("interview_id");

                    b.ToTable("Interview_Panel", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate", b =>
                {
                    b.Property<string>("CandidateId")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("DocUpload")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResumePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CandidateId");

                    b.HasIndex(new[] { "Email" }, "UQ_Candidates_Email")
                        .IsUnique();

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("ReviewId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Candidate_Reviews");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Skill", b =>
                {
                    b.Property<int>("CandidateSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateSkillId"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("CandidateSkillId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillId");

                    b.ToTable("Candidate_Skills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Status_History", b =>
                {
                    b.Property<int>("CandidateStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateStatusId"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CandidateStatusId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("JobId");

                    b.ToTable("Candidate_Status_History", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.EmailMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("RecruitmentApi.Models.EmailRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailMessageId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId");

                    b.ToTable("EmailRecipients");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Employee_Record", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("OfferLetterPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("JobId");

                    b.HasIndex(new[] { "CandidateId" }, "UQ_Employee_Records_Candidate")
                        .IsUnique();

                    b.ToTable("Employee_Records");
                });

            modelBuilder.Entity("RecruitmentApi.Models.HR_Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("AdaptabilityRating")
                        .HasColumnType("int");

                    b.Property<string>("AreasForImprovement")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CareerPathNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CommunicationRating")
                        .HasColumnType("int");

                    b.Property<int>("InterviewId")
                        .HasColumnType("int");

                    b.Property<int>("LeadershipRating")
                        .HasColumnType("int");

                    b.Property<int>("OverallRating")
                        .HasColumnType("int");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TeamworkRating")
                        .HasColumnType("int");

                    b.Property<string>("TrainingRecommendations")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("ReviewId");

                    b.HasIndex("InterviewId");

                    b.HasIndex("UserId");

                    b.ToTable("HR_Review", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewId"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewTypeId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("LocationOrLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("ScheduledBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InterviewId")
                        .HasName("PK_Interviews");

                    b.HasIndex("CandidateId");

                    b.HasIndex("InterviewTypeId");

                    b.HasIndex("JobId");

                    b.HasIndex("ScheduledBy");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview_Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int>("CandidateSkillId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConceptRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("FeedbackAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("InterviewId")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalRating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("FeedbackId");

                    b.HasIndex("CandidateSkillId");

                    b.HasIndex("InterviewId");

                    b.HasIndex("UserId");

                    b.ToTable("Interview_Feedback", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview_Type", b =>
                {
                    b.Property<int>("InterviewTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewTypeId"));

                    b.Property<string>("InterviewRoundName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessDescreption")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("InterviewTypeId");

                    b.ToTable("Interview_Type", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Scheduled")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StatusId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("SkillId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("Jobs_Skills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.HasIndex("ChangedBy");

                    b.ToTable("Jobs_Status", (string)null);
                });

            modelBuilder.Entity("RecruitmentApi.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unread");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillId");

                    b.HasIndex(new[] { "SkillName" }, "UQ_Skills_Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Users_Role", b =>
                {
                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.HasKey("role_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("Users_Roles", (string)null);
                });

            modelBuilder.Entity("Candidate_Document", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "Candidate")
                        .WithMany("CandidateDocuments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Documents_Candidates");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Interview_Panel", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Interview", null)
                        .WithMany()
                        .HasForeignKey("interview_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Panel_Interviews");

                    b.HasOne("RecruitmentApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Panel_Users");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Review", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "Candidate")
                        .WithMany("CandidateReviews")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Reviews_Candidates");

                    b.HasOne("RecruitmentApi.Models.Job", "Job")
                        .WithMany("CandidateReviews")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Reviews_Jobs");

                    b.HasOne("RecruitmentApi.Models.User", "User")
                        .WithMany("CandidateReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Reviews_Users");

                    b.Navigation("Candidate");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Skill", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Skills_Candidates");

                    b.HasOne("RecruitmentApi.Models.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Skills_Skills");

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Status_History", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "Candidate")
                        .WithMany("CandidateStatusHistories")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Status_History_Candidates");

                    b.HasOne("RecruitmentApi.Models.User", "ChangedByUser")
                        .WithMany("CandidateStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Status_History_Users");

                    b.HasOne("RecruitmentApi.Models.Job", "Job")
                        .WithMany("CandidateStatusHistories")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Candidate_Status_History_Jobs");

                    b.Navigation("Candidate");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentApi.Models.EmailRecipient", b =>
                {
                    b.HasOne("RecruitmentApi.Models.EmailMessage", "EmailMessage")
                        .WithMany("Recipients")
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Employee_Record", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "Candidate")
                        .WithOne("EmployeeRecord")
                        .HasForeignKey("RecruitmentApi.Models.Employee_Record", "CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Records_Candidates");

                    b.HasOne("RecruitmentApi.Models.Job", "Job")
                        .WithMany("EmployeeRecords")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Records_Jobs");

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("RecruitmentApi.Models.HR_Review", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Interview", "Interview")
                        .WithMany("HrReviews")
                        .HasForeignKey("InterviewId")
                        .IsRequired()
                        .HasConstraintName("FK_HR_Review_Interviews");

                    b.HasOne("RecruitmentApi.Models.User", "User")
                        .WithMany("HrReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_HR_Review_Users");

                    b.Navigation("Interview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate", "Candidate")
                        .WithMany("Interviews")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Interviews_Candidates");

                    b.HasOne("RecruitmentApi.Models.Interview_Type", "InterviewType")
                        .WithMany("Interviews")
                        .HasForeignKey("InterviewTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Interviews_Interview_Type");

                    b.HasOne("RecruitmentApi.Models.Job", "Job")
                        .WithMany("Interviews")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Interviews_Jobs");

                    b.HasOne("RecruitmentApi.Models.User", "ScheduledByUser")
                        .WithMany("ScheduledInterviews")
                        .HasForeignKey("ScheduledBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Interviews_Users");

                    b.Navigation("Candidate");

                    b.Navigation("InterviewType");

                    b.Navigation("Job");

                    b.Navigation("ScheduledByUser");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview_Feedback", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Candidate_Skill", "CandidateSkill")
                        .WithMany("InterviewFeedbacks")
                        .HasForeignKey("CandidateSkillId")
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Feedback_CandidateSkills");

                    b.HasOne("RecruitmentApi.Models.Interview", "Interview")
                        .WithMany("InterviewFeedbacks")
                        .HasForeignKey("InterviewId")
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Feedback_Interviews");

                    b.HasOne("RecruitmentApi.Models.User", "User")
                        .WithMany("InterviewFeedbacks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Interview_Feedback_Users");

                    b.Navigation("CandidateSkill");

                    b.Navigation("Interview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Job", b =>
                {
                    b.HasOne("RecruitmentApi.Models.User", "CreatedByUser")
                        .WithMany("Jobs")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Users");

                    b.HasOne("RecruitmentApi.Models.Jobs_Status", "Status")
                        .WithMany("Jobs")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Jobs_Status");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Skill", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Job", "Job")
                        .WithMany("JobsSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Skills_Jobs");

                    b.HasOne("RecruitmentApi.Models.Skill", "Skill")
                        .WithMany("JobsSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Skills_Skills");

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Status", b =>
                {
                    b.HasOne("RecruitmentApi.Models.User", "ChangedByUser")
                        .WithMany("JobsStatuses")
                        .HasForeignKey("ChangedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Jobs_Status_Users");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Notification", b =>
                {
                    b.HasOne("RecruitmentApi.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Users_Role", b =>
                {
                    b.HasOne("RecruitmentApi.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles_Roles");

                    b.HasOne("RecruitmentApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles_Users");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate", b =>
                {
                    b.Navigation("CandidateDocuments");

                    b.Navigation("CandidateReviews");

                    b.Navigation("CandidateSkills");

                    b.Navigation("CandidateStatusHistories");

                    b.Navigation("EmployeeRecord");

                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Candidate_Skill", b =>
                {
                    b.Navigation("InterviewFeedbacks");
                });

            modelBuilder.Entity("RecruitmentApi.Models.EmailMessage", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview", b =>
                {
                    b.Navigation("HrReviews");

                    b.Navigation("InterviewFeedbacks");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Interview_Type", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Job", b =>
                {
                    b.Navigation("CandidateReviews");

                    b.Navigation("CandidateStatusHistories");

                    b.Navigation("EmployeeRecords");

                    b.Navigation("Interviews");

                    b.Navigation("JobsSkills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Jobs_Status", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("RecruitmentApi.Models.Skill", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("JobsSkills");
                });

            modelBuilder.Entity("RecruitmentApi.Models.User", b =>
                {
                    b.Navigation("CandidateReviews");

                    b.Navigation("CandidateStatusHistories");

                    b.Navigation("HrReviews");

                    b.Navigation("InterviewFeedbacks");

                    b.Navigation("Jobs");

                    b.Navigation("JobsStatuses");

                    b.Navigation("Notifications");

                    b.Navigation("ScheduledInterviews");
                });
#pragma warning restore 612, 618
        }
    }
}
